const kirby = {
  '341': 'Jump 2',
  '342': 'Jump 3',
  '343': 'Jump 4',
  '344': 'Jump 5',
  '345': 'Jump 6',
  '346': 'Jump 2 With Hat',
  '347': 'Jump 3 With Hat',
  '348': 'Jump 4 With Hat',
  '349': 'Jump 5 With Hat',
  '350': 'Jump 6 With Hat',
  '351': 'Dash Attack Ground',
  '352': 'Dash Attack Air',
  '353': 'Swallow Ground Startup',
  '354': 'Swallow Ground Loop',
  '355': 'Swallow Ground End',
  '356': 'Swallow Ground Capture',
  '357': '???',
  '358': 'Swallow Ground Captured',
  '359': 'Swallow Ground Capture Wait',
  '360': 'Swallow Capture Walk Slow',
  '361': 'Swallow Capture Walk Middle',
  '362': 'Swallow Capture Walk Fast',
  '363': 'Swallow Ground Capture Turn',
  '364': 'Swallow Capture Jump Squat',
  '365': 'Swallow Capture Jump',
  '366': 'Swallow Capture Landing',
  '367': 'Swallow Ground Digest',
  '368': '???',
  '369': 'Swallow Ground Spit',
  '370': '???',
  '371': 'Swallow Air Startup',
  '372': 'Swallow Air Loop',
  '373': 'Swallow Air End',
  '374': 'Swallow Air Capture',
  '375': '???',
  '376': 'Swallow Air Captured',
  '377': 'Swallow Air Capture Wait',
  '378': 'Swallow Air Digest',
  '379': '???',
  '380': 'Swallow Air Spit',
  '381': '???',
  '382': 'Swallow Air Capture Turn',
  '383': 'Hammer Ground',
  '384': 'Hammer Air',
  '385': 'Final Cutter Ground Startup',
  '386': '???',
  '387': '???',
  '388': 'Final Cutter Ground End',
  '389': 'Final Cutter Air Startup',
  '390': 'Final Cutter Air Apex',
  '391': 'Final Cutter Sword Descent',
  '392': 'Final Cutter Air End',
  '393': 'Stone Ground Startup',
  '394': 'Stone Ground',
  '395': 'Stone Ground End',
  '396': 'Stone Air Startup',
  '397': 'Stone Air',
  '398': 'Stone Air End',
  '399': 'Mario Fireball Ground',
  '400': 'Mario Fireball Air',
  '401': 'Link Bow Ground Charge',
  '402': 'Link Bow Ground Fully Charged',
  '403': 'Link Bow Ground Fire',
  '404': 'Link Bow Air Charge',
  '405': 'Link Bow Air Fully Charged',
  '406': 'Link Bow Air Fire',
  '407': 'Samus Charge Shot Ground Start',
  '408': 'Samus Charge Shot Ground Loop',
  '409': 'Samus Charge Shot Ground End',
  '410': 'Samus Charge Shot Ground Fire',
  '411': 'Samus Charge Shot Air Start',
  '412': 'Samus Charge Shot Air Fire',
  '413': 'Yoshi Egg Lay Ground',
  '414': 'Yoshi Egg Lay Ground Capture Start',
  '415': '???',
  '416': 'Yoshi Egg Lay Ground Capture',
  '417': '???',
  '418': 'Yoshi Egg Lay Air',
  '419': 'Yoshi Egg Lay Air Capture Start',
  '420': '???',
  '421': 'Yoshi Egg Lay Air Capture',
  '422': '???',
  '423': 'Fox Blaster Ground Startup',
  '424': 'Fox Blaster Ground Loop',
  '425': 'Fox Blaster Ground End',
  '426': 'Fox Blaster Air Startup',
  '427': 'Fox Blaster Air Loop',
  '428': 'Fox Blaster Air End',
  '429': 'Pikachu Thunder Jolt Ground',
  '430': 'Pikachu Thunder Jolt Air',
  '431': 'Luigi Fireball Ground',
  '432': 'Luigi Fireball Air',
  '433': 'Falcon Falcon Punch Ground',
  '434': 'Falcon Falcon Punch Air',
  '435': 'Ness PK Flash Ground Startup',
  '436': 'Ness PK Flash Ground Charge',
  '437': 'Ness PK Flash Ground Explode',
  '438': 'Ness PK Flash Ground End',
  '439': 'Ness PK Flash Air Startup',
  '440': 'Ness PK Flash Air Charge',
  '441': 'Ness PK Flash Air Explode',
  '442': 'Ness PK Flash Air End',
  '443': 'Bowser Fire Breath Ground Start',
  '444': 'Bowser Fire Breath Ground Loop',
  '445': 'Bowser Fire Breath Ground End',
  '446': 'Bowser Fire Breath Air Start',
  '447': 'Bowser Fire Breath Air Loop',
  '448': 'Bowser Fire Breath Air End',
  '449': 'Peach Toad Ground',
  '450': 'Peach Toad Ground Attack',
  '451': 'Peach Toad Air',
  '452': 'Peach Toad Air Attack',
  '453': 'Ice Climbers Ice Shot Ground',
  '454': 'Ice Climbers Ice Shot Air',
  '455': 'DK Giant Punch Ground Charge Startup',
  '456': 'DK Giant Punch Ground Charge Loop',
  '457': 'DK Giant Punch Ground Charge Stop',
  '458': 'DK Giant Punch Ground Early Punch',
  '459': 'DK Giant Punch Ground Full Charge Punch',
  '460': 'DK Giant Punch Air Charge Startup',
  '461': 'DK Giant Punch Air Charge Loop',
  '462': 'DK Giant Punch Air Charge Stop',
  '463': 'DK Giant Punch Air Early Punch',
  '464': 'DK Giant Punch Air Full Charge Punch',
  '465': "Zelda Nayru's Love Ground",
  '466': "Zelda Nayru's Love Air",
  '467': 'Sheik Needle Storm Ground Start Charge',
  '468': 'Sheik Needle Storm Ground Charge Loop',
  '469': 'Sheik Needle Storm Ground End Charge',
  '470': 'Sheik Needle Storm Ground Fire',
  '471': 'Sheik Needle Storm Air Start Charge',
  '472': 'Sheik Needle Storm Air Charge Loop',
  '473': 'Sheik Needle Storm Air End Charge',
  '474': 'Sheik Needle Storm Air Fire',
  '475': 'Jigglypuff Rollout Ground Start Charge Right',
  '476': 'Jigglypuff Rollout Ground Start Charge Left',
  '477': 'Jigglypuff Rollout Ground Charge Loop',
  '478': 'Jigglypuff Rollout Ground Fully Charged',
  '479': 'Jigglypuff Rollout Ground Charge Release',
  '480': 'Jigglypuff Rollout Ground Start Turn',
  '481': 'Jigglypuff Rollout Ground End Right',
  '482': 'Jigglypuff Rollout Ground End Left',
  '483': 'Jigglypuff Rollout Air Start Charge Right',
  '484': 'Jigglypuff Rollout Air Start Charge Left',
  '485': 'Jigglypuff Rollout Air Charge Loop',
  '486': 'Jigglypuff Rollout Air Fully Charged',
  '487': 'Jigglypuff Rollout Air Charge Release',
  '488': '???',
  '489': 'Jigglypuff Rollout Air End Right',
  '490': 'Jigglypuff Rollout Air End Left',
  '491': 'Jigglypuff Rollout Hit',
  '492': 'Marth Shield Breaker Ground Start Charge',
  '493': 'Marth Shield Breaker Ground Charge Loop',
  '494': 'Marth Shield Breaker Ground Early Release',
  '495': 'Marth Shield Breaker Ground Fully Charged',
  '496': 'Marth Shield Breaker Air Start Charge',
  '497': 'Marth Shield Breaker Air Charge Loop',
  '498': 'Marth Shield Breaker Air Early Release',
  '499': 'Marth Shield Breaker Air Fully Charged',
  '500': 'Mewtwo Shadow Ball Ground Start Charge',
  '501': 'Mewtwo Shadow Ball Ground Charge Loop',
  '502': 'Mewtwo Shadow Ball Ground Fully Charged',
  '503': 'Mewtwo Shadow Ball Ground End Charge',
  '504': 'Mewtwo Shadow Ball Ground Fire',
  '505': 'Mewtwo Shadow Ball Air Start Charge',
  '506': 'Mewtwo Shadow Ball Air Charge Loop',
  '507': 'Mewtwo Shadow Ball Air Fully Charged',
  '508': 'Mewtwo Shadow Ball Air End Charge',
  '509': 'Mewtwo Shadow Ball Air Fire',
  '510': 'Game and Watch Oil Panic Ground',
  '511': 'Game and Watch Oil Panic Air',
  '512': 'Doc Megavitamin Ground',
  '513': 'Doc Megavitamin Air',
  '514': 'Young Link Fire Bow Ground Charge',
  '515': 'Young Link Fire Bow Ground Fully Charged',
  '516': 'Young Link Fire Bow Ground Fire',
  '517': 'Young Link Fire Bow Air Charge',
  '518': 'Young Link Fire Bow Air Fully Charged',
  '519': 'Young Link Fire Bow Air Fire',
  '520': 'Falco Blaster Ground Startup',
  '521': 'Falco Blaster Ground Loop',
  '522': 'Falco Blaster Ground End',
  '523': 'Falco Blaster Air Startup',
  '524': 'Falco Blaster Air Loop',
  '525': 'Falco Blaster Air End',
  '526': 'Pichu Thunder Jolt Ground',
  '527': 'Pichu Thunder Jolt Air',
  '528': 'Ganon Warlock Punch Ground',
  '529': 'Ganon Warlock Punch Air',
  '530': 'Roy Flare Blade Ground Start Charge',
  '531': 'Roy Flare Blade Ground Charge Loop',
  '532': 'Roy Flare Blade Ground Early Release',
  '533': 'Roy Flare Blade Ground Fully Charged',
  '534': 'Roy Flare Blade Air Start Charge',
  '535': 'Roy Flare Blade Air Charge Loop',
  '536': 'Roy Flare Blade Air Early Release',
  '537': 'Roy Flare Blade Air Fully Charged',
};

export const specials = {
  // Bowser
  5: {
    '341': 'Fire Breath Ground Startup',
    '342': 'Fire Breath Ground Loop',
    '343': 'Fire Breath Ground End',
    '344': 'Fire Breath Air Startup',
    '345': 'Fire Breath Air Loop',
    '346': 'Fire Breath Air End',
    '347': 'Koopa Klaw Ground',
    '348': 'Koopa Klaw Ground Grab',
    '349': 'Koopa Klaw Ground Pummel',
    '350': 'Koopa Klaw Ground Wait',
    '351': 'Koopa Klaw Ground Throw F',
    '352': 'Koopa Klaw Ground Throw B',
    '353': 'Koopa Klaw Air',
    '354': 'Koopa Klaw Air Grab',
    '355': 'Koopa Klaw Air Pummel',
    '356': 'Koopa Klaw Air Wait',
    '357': 'Koopa Klaw Air Throw F',
    '358': 'Koopa Klaw Air Throw B',
    '359': 'Whirling Fortress Ground',
    '360': 'Whirling Fortress Air',
    '361': 'Bomb Ground Begin',
    '362': 'Bomb Air',
    '363': 'Bomb Land',
  },
  // Captain Falcon
  2: {
    '347': 'Falcon Punch Ground',
    '348': 'Falcon Punch Air',
    '349': 'Raptor Boost Ground',
    '350': 'Raptor Boost Ground Hit',
    '351': 'Raptor Boost Air',
    '352': 'Raptor Boost Air Hit',
    '353': 'Falcon Dive Ground',
    '354': 'Falcon Dive Air',
    '355': 'Falcon Dive Catch',
    '356': 'Falcon Dive Ending',
    '357': 'Falcon Kick Ground',
    '358': 'Falcon Kick Ground Ending On Ground',
    '359': 'Falcon Kick Air',
    '360': 'Falcon Kick Air Ending On Ground',
    '361': 'Falcon Kick Air Ending In Air',
    '362': 'Falcon Kick Ground Ending In Air',
    '363': 'Falcon Kick Hit Wall',
  },
  // Donkey Kong
  3: {
    '351': 'Kong Karry Wait',
    '352': 'Kong Karry Walk Slow',
    '353': 'Kong Karry Walk Middle',
    '354': 'Kong Karry Walk Fast',
    '355': 'Kong Karry Turn',
    '356': 'Kong Karry Jump Squat',
    '357': 'Kong Karry Fall',
    '358': 'Kong Karry Jump',
    '359': 'Kong Karry Landing',
    '361': 'Kong Karry Ground Throw Forward',
    '362': 'Kong Karry Ground Throw Backward',
    '363': 'Kong Karry Ground Throw Up',
    '364': 'Kong Karry Ground Throw Down',
    '365': 'Kong Karry Air Throw Forward',
    '366': 'Kong Karry Air Throw Backward',
    '367': 'Kong Karry Air Throw Up',
    '368': 'Kong Karry Air Throw Down',
    '369': 'Giant Punch Ground Charge Startup',
    '370': 'Giant Punch Ground Charge Loop',
    '371': 'Giant Punch Ground Charge Stop',
    '372': 'Giant Punch Ground Early Punch',
    '373': 'Giant Punch Ground Full Charge Punch',
    '374': 'Giant Punch Air Charge Startup',
    '375': 'Giant Punch Air Charge Loop',
    '376': 'Giant Punch Air Charge Stop',
    '377': 'Giant Punch Air Early Punch',
    '378': 'Giant Punch Air Full Charge Punch',
    '379': 'Headbutt Ground',
    '380': 'Headbutt Air',
    '381': 'Spinning Kong Ground',
    '382': 'Spinning Kong Air',
    '383': 'Hand Slap Startup',
    '384': 'Hand Slap Loop',
    '385': 'Hand Slap End',
  },
  // Dr. Mario
  21: {
    '341': 'Taunt R',
    '343': 'Megavitamin Ground',
    '344': 'Megavitamin Air',
    '345': 'Super Sheet Ground',
    '346': 'Super Sheet Air',
    '347': 'Super Jump Punch Ground',
    '348': 'Super Jump Punch Air',
    '349': 'Tornado Ground',
    '350': 'Tornado Air',
  },
  // Falco
  22: {
    '341': 'Blaster Ground Startup',
    '342': 'Blaster Ground Loop',
    '343': 'Blaster Ground End',
    '344': 'Blaster Air Startup',
    '345': 'Blaster Air Loop',
    '346': 'Blaster Air End',
    '347': 'Phantasm Ground Startup',
    '348': 'Phantasm Ground',
    '349': 'Phantasm Ground End',
    '350': 'Phantasm Startup Air',
    '351': 'Phantasm Air',
    '352': 'Phantasm Air End',
    '353': 'Fire Bird Ground Startup',
    '354': 'Fire Bird Air Startup',
    '355': 'Fire Bird Ground',
    '356': 'Fire Bird Air',
    '357': 'Fire Bird Ground End',
    '358': 'Fire Bird Air End',
    '359': 'Fire Bird Bounce End',
    '360': 'Reflector Ground Startup',
    '361': 'Reflector Ground Loop',
    '362': 'Reflector Ground Reflect',
    '363': 'Reflector Ground End',
    '364': 'Reflector Ground Change Direction',
    '365': 'Reflector Air Startup',
    '366': 'Reflector Air Loop',
    '367': 'Reflector Air Reflect',
    '368': 'Reflector Air End',
    '369': 'Reflector Air Change Direction',
    '370': 'Smash Taunt Right Startup',
    '371': 'Smash Taunt Left Startup',
    '372': 'Smash Taunt Right Rise',
    '373': 'Smash Taunt Left Rise',
    '374': 'Smash Taunt Right Finish',
    '375': 'Smash Taunt Left Finish',
  },
  // Fox
  1: {
    '341': 'Blaster Ground Startup',
    '342': 'Blaster Ground Loop',
    '343': 'Blaster Ground End',
    '344': 'Blaster Air Startup',
    '345': 'Blaster Air Loop',
    '346': 'Blaster Air End',
    '347': 'Illusion Ground Startup',
    '348': 'Illusion Ground',
    '349': 'Illusion Ground End',
    '350': 'Illusion Startup Air',
    '351': 'Illusion Air',
    '352': 'Illusion Air End',
    '353': 'Fire Fox Ground Startup',
    '354': 'Fire Fox Air Startup',
    '355': 'Fire Fox Ground',
    '356': 'Fire Fox Air',
    '357': 'Fire Fox Ground End',
    '358': 'Fire Fox Air End',
    '359': 'Fire Fox Bounce End',
    '360': 'Reflector Ground Startup',
    '361': 'Reflector Ground Loop',
    '362': 'Reflector Ground Reflect',
    '363': 'Reflector Ground End',
    '364': 'Reflector Ground Change Direction',
    '365': 'Reflector Air Startup',
    '366': 'Reflector Air Loop',
    '367': 'Reflector Air Reflect',
    '368': 'Reflector Air End',
    '369': 'Reflector Air Change Direction',
    '370': 'Smash Taunt Right Startup',
    '371': 'Smash Taunt Left Startup',
    '372': 'Smash Taunt Right Rise',
    '373': 'Smash Taunt Left Rise',
    '374': 'Smash Taunt Right Finish',
    '375': 'Smash Taunt Left Finish',
  },
  // Ganondorf
  25: {
    '347': 'Warlock Punch Ground',
    '348': 'Warlock Punch Air',
    '349': 'Gerudo Dragon Ground',
    '350': 'Gerudo Dragon Ground Hit',
    '351': 'Gerudo Dragon Air',
    '352': 'Gerudo Dragon Air Hit',
    '353': 'Dark Dive Ground',
    '354': 'Dark Dive Air',
    '355': 'Dark Dive Catch',
    '356': 'Dark Dive Ending',
    '357': "Wizard's Foot Ground",
    '358': "Wizard's Foot Ground Ending On Ground",
    '359': "Wizard's Foot Air",
    '360': "Wizard's Foot Air Ending On Ground",
    '361': "Wizard's Foot Air Ending In Air",
    '362': "Wizard's Foot Ground Ending In Air",
    '363': "Wizard's Foot Hit Wall",
  },
  // Ice Climbers
  10: {
    '341': 'Ice Shot Ground',
    '342': 'Ice Shot Air',
    '343': 'Popo Squall Hammer Ground Solo',
    '344': 'Popo Squall Hammer Ground Together',
    '345': 'Popo Squall Hammer Air Solo',
    '346': 'Popo Squall Hammer Air Together',
    '347': 'Popo Belay Ground Startup',
    '348': 'Popo Belay Ground Catapulting Nana',
    '350': 'Popo Belay Ground Failed Catapulting',
    '351': 'Popo Belay Ground Failed Catapulting End',
    '352': 'Popo Belay Air Startup',
    '353': 'Popo Belay Air Catapulting Nana',
    '354': 'Popo Belay Catapulting',
    '355': 'Popo Belay Air Failed Catapulting',
    '356': 'Popo Belay Air Failed Catapulting End',
    '357': 'Blizzard Ground',
    '358': 'Blizzard Air',
    '359': 'Nana Squall Hammer Ground Together',
    '360': 'Nana Squall Hammer Air Together',
    '361': 'Nana Belay Catapult Startup',
    '362': 'Nana Belay Ground Catapult End',
    '365': 'Nana Belay Catapulting',
  },
  // Jigglypuff
  15: {
    '360': 'Rollout Air End Right',
    '361': 'Rollout Air End Left',
    '362': 'Rollout Hit',
    '363': 'Pound Ground',
    '364': 'Pound Air',
    '365': 'Sing Ground Left',
    '366': 'Sing Air Left',
    '367': 'Sing Ground Right',
    '368': 'Sing Air Right',
    '369': 'Rest Ground Left',
    '370': 'Rest Air Left',
    '371': 'Rest Ground Right',
    '372': 'Rest Air Right',
  },
  // Kirby
  4: kirby,
  // Link
  6: {
    '341': 'Side Smash 2',
    '342': '???',
    '343': '???',
    '344': 'Bow Ground Charge',
    '345': 'Bow Ground Fully Charged',
    '346': 'Bow Ground Fire',
    '347': 'Bow Air Charge',
    '348': 'Bow Air Fully Charged',
    '349': 'Bow Air Fire',
    '350': 'Boomerang Ground Throw',
    '351': 'Boomerang Ground Catch',
    '352': 'Boomerang Ground Throw Empty',
    '353': 'Boomerang Air Throw',
    '354': 'Boomerang Air Catch',
    '355': 'Boomerang Air Throw Empty',
    '356': 'Spin Attack Ground',
    '357': 'Spin Attack Air',
    '358': 'Bomb Ground',
    '359': 'Bomb Air',
    '360': 'Zair',
    '361': 'Zair Catch',
  },
  // Luigi
  17: {
    '341': 'Fireball Ground',
    '342': 'Fireball Air',
    '343': 'Green Missile Ground Startup',
    '344': 'Green Missile Ground Charge',
    '346': 'Green Missile Ground Landing',
    '347': 'Green Missile Ground Takeoff',
    '348': 'Green Missile Ground Takeoff Misfire',
    '349': 'Green Missile Air Startup',
    '350': 'Green Missile Air Charge',
    '351': 'Green Missile Air',
    '352': 'Green Missile Air End',
    '353': 'Green Missile Air Takeoff',
    '354': 'Green Missile Air Takeoff Misfire',
    '355': 'Super Jump Punch Ground',
    '356': 'Super Jump Punch Air',
    '357': 'Cyclone Ground',
    '358': 'Cyclone Air',
  },
  // Mario
  0: {
    '343': 'Fireball Ground',
    '344': 'Fireball Air',
    '345': 'Cape Ground',
    '346': 'Cape Air',
    '347': 'Super Jump Punch Ground',
    '348': 'Super Jump Punch Air',
    '349': 'Tornado Ground',
    '350': 'Tornado Air',
  },
  // Marth
  18: {
    '341': 'Shield Breaker Ground Start Charge',
    '342': 'Shield Breaker Ground Charge Loop',
    '343': 'Shield Breaker Ground Early Release',
    '344': 'Shield Breaker Ground Fully Charged',
    '345': 'Shield Breaker Air Start Charge',
    '346': 'Shield Breaker Air Charge Loop',
    '347': 'Shield Breaker Air Early Release',
    '348': 'Shield Breaker Air Fully Charged',
    '349': 'Dancing Blade 1 Ground',
    '350': 'Dancing Blade 2 Up Ground',
    '351': 'Dancing Blade 2 Side Ground',
    '352': 'Dancing Blade 3 Up Ground',
    '353': 'Dancing Blade 3 Side Ground',
    '354': 'Dancing Blade 3 Down Ground',
    '355': 'Dancing Blade 4 Up Ground',
    '356': 'Dancing Blade 4 Side Ground',
    '357': 'Dancing Blade 4 Down Ground',
    '358': 'Dancing Blade 1 Air',
    '359': 'Dancing Blade 2 Up Air',
    '360': 'Dancing Blade 2 Side Air',
    '361': 'Dancing Blade 3 Up Air',
    '362': 'Dancing Blade 3 Side Air',
    '363': 'Dancing Blade 3 Down Air',
    '364': 'Dancing Blade 4 Up Air',
    '365': 'Dancing Blade 4 Side Air',
    '366': 'Dancing Blade 4 Down Air',
    '367': 'Dolphin Slash Ground',
    '368': 'Dolphin Slash Air',
    '369': 'Counter Ground',
    '370': 'Counter Ground Hit',
    '371': 'Counter Air',
    '372': 'Counter Air Hit',
  },
  // Mewtwo
  16: {
    '341': 'Shadow Ball Ground Start Charge',
    '342': 'Shadow Ball Ground Charge Loop',
    '343': 'Shadow Ball Ground Fully Charged',
    '344': 'Shadow Ball Ground End Charge',
    '345': 'Shadow Ball Ground Fire',
    '346': 'Shadow Ball Air Start Charge',
    '347': 'Shadow Ball Air Charge Loop',
    '348': 'Shadow Ball Air Fully Charged',
    '349': 'Shadow Ball Air End Charge',
    '350': 'Shadow Ball Air Fire',
    '351': 'Confusion Ground',
    '352': 'Confusion Air',
    '353': 'Teleport Ground Startup',
    '354': 'Teleport Ground Disappear',
    '355': 'Teleport Ground Reappear',
    '356': 'Teleport Air Startup',
    '357': 'Teleport Air Disappear',
    '358': 'Teleport Air Reappear',
    '359': 'Disable Ground',
    '360': 'Disable Air',
  },
  // Mr. Game and Watch
  24: {
    '341': 'Jab',
    '342': 'Jab 2',
    '343': 'Rapid Jabs',
    '344': 'Rapid Jabs End',
    '345': 'Down Tilt',
    '346': 'Side Smash',
    '347': 'Nair',
    '348': 'Bair',
    '349': 'Uair',
    '350': 'Nair Landing',
    '351': 'Bair Landing',
    '352': 'Uair Landing',
    '353': 'Chef Ground',
    '354': 'Chef Air',
    '355': 'Judgment 1 Ground',
    '356': 'Judgment 2 Ground',
    '357': 'Judgment 3 Ground',
    '358': 'Judgment 4 Ground',
    '359': 'Judgment 5 Ground',
    '360': 'Judgment 6 Ground',
    '361': 'Judgment 7 Ground',
    '362': 'Judgment 8 Ground',
    '363': 'Judgment 9 Ground',
    '364': 'Judgment 1 Air',
    '365': 'Judgment 2 Air',
    '366': 'Judgment 3 Air',
    '367': 'Judgment 4 Air',
    '368': 'Judgment 5 Air',
    '369': 'Judgment 6 Air',
    '370': 'Judgment 7 Air',
    '371': 'Judgment 8 Air',
    '372': 'Judgment 9 Air',
    '373': 'Fire Ground',
    '374': 'Fire Air',
    '375': 'Oil Panic Ground',
    '376': 'Oil Panic Ground Absorb',
    '377': 'Oil Panic Ground Spill',
    '378': 'Oil Panic Air',
    '379': 'Oil Panic Air Absorb',
    '380': 'Oil Panic Air Spill',
  },
  // Ness
  8: {
    '341': 'Side Smash',
    '342': 'Up Smash',
    '343': 'Up Smash Charge',
    '344': 'Up Smash Charged',
    '345': 'Down Smash',
    '346': 'Down Smash Charge',
    '347': 'Down Smash Charged',
    '348': 'PK Flash Ground Startup',
    '349': 'PK Flash Ground Charge',
    '350': 'PK Flash Ground Explode',
    '351': 'PK Flash Ground End',
    '352': 'PK Flash Air Startup',
    '353': 'PK Flash Air Charge',
    '354': 'PK Flash Air Explode',
    '355': 'PK Flash Air End',
    '356': 'PK Fire Ground',
    '357': 'PK Fire Air',
    '358': 'PK Thunder Ground Startup',
    '359': 'PK Thunder Ground',
    '360': 'PK Thunder Ground End',
    '361': 'PK Thunder Ground Hit',
    '362': 'PK Thunder Air Startup',
    '363': 'PK Thunder Air',
    '364': 'PK Thunder Air End',
    '365': 'PK Thunder Air Hit',
    '366': 'PK Thunder Air Hit Wall',
    '367': 'PSI Magnet Ground Startup',
    '368': 'PSI Magnet Ground Loop',
    '369': 'PSI Magnet Ground Absorb',
    '370': 'PSI Magnet Ground End',
    '371': '??',
    '372': 'PSI Magnet Air Startup',
    '373': 'PSI Magnet Air Loop',
    '374': 'PSI Magnet Air Absorb',
    '375': 'PSI Magnet Air End',
  },
  // Peach
  9: {
    '341': 'Float',
    '342': 'Float End Forward',
    '343': 'Float End Backward',
    '344': 'Float Nair',
    '345': 'Float Fair',
    '346': 'Float Bair',
    '347': 'Float Uair',
    '348': 'Float Dair',
    '349': 'Side Smash Golf Club',
    '350': 'Side Smash Frying Pan',
    '351': 'Side Smash Tennis Racket',
    '352': 'Vegetable Ground',
    '353': 'Vegetable Air',
    '354': 'Bomber Ground Startup',
    '355': 'Bomber Ground End',
    '356': '???',
    '357': 'Bomber Air Startup',
    '358': 'Bomber Air End',
    '359': 'Bomber Air Hit',
    '360': 'Bomber Air',
    '361': 'Parasol Ground Start',
    '362': '???',
    '363': 'Parasol Air Start',
    '364': '???',
    '365': 'Toad Ground',
    '366': 'Toad Ground Attack',
    '367': 'Toad Air',
    '368': 'Toad Air Attack',
    '369': 'Parasol Opening',
    '370': 'Parasol Open',
  },
  // Pichu
  23: {
    '341': 'Thunder Jolt Ground',
    '342': 'Thunder Jolt Air',
    '343': 'Skull Bash Ground Startup',
    '344': 'Skull Bash Ground Charge',
    '345': '???',
    '346': 'Skull Bash Ground Landing',
    '347': 'Skull Bash Ground Takeoff',
    '348': 'Skull Bash Air Startup',
    '349': 'Skull Bash Air Charge',
    '350': 'Skull Bash Air',
    '351': 'Skull Bash Air End',
    '352': 'Skull Bash Air Takeoff',
    '353': 'Agility Ground Startup',
    '354': 'Agility Ground',
    '355': 'Agility Ground End',
    '356': 'Agility Air Startup',
    '357': 'Agility Air',
    '358': 'Agility Air End',
    '359': 'Thunder Ground Startup',
    '360': 'Thunder Ground',
    '361': 'Thunder Ground Hit',
    '362': 'Thunder Ground End',
    '363': 'Thunder Air Startup',
    '364': 'Thunder Air',
    '365': 'Thunder Air Hit',
    '366': 'Thunder Air End',
  },
  // Pikachu
  12: {
    '341': 'Thunder Jolt Ground',
    '342': 'Thunder Jolt Air',
    '343': 'Skull Bash Ground Startup',
    '344': 'Skull Bash Ground Charge',
    '345': '???',
    '346': 'Skull Bash Ground Landing',
    '347': 'Skull Bash Ground Takeoff',
    '348': 'Skull Bash Air Startup',
    '349': 'Skull Bash Air Charge',
    '350': 'Skull Bash Air',
    '351': 'Skull Bash Air End',
    '352': 'Skull Bash Air Takeoff',
    '353': 'Quick Attack Ground Startup',
    '354': 'Quick Attack Ground',
    '355': 'Quick Attack Ground End',
    '356': 'Quick Attack Air Startup',
    '357': 'Quick Attack Air',
    '358': 'Quick Attack Air End',
    '359': 'Thunder Ground Startup',
    '360': 'Thunder Ground',
    '361': 'Thunder Ground Hit',
    '362': 'Thunder Ground End',
    '363': 'Thunder Air Startup',
    '364': 'Thunder Air',
    '365': 'Thunder Air Hit',
    '366': 'Thunder Air End',
  },
  // Roy
  26: {
    '341': 'Flare Blade Ground Start Charge',
    '342': 'Flare Blade Ground Charge Loop',
    '343': 'Flare Blade Ground Early Release',
    '344': 'Flare Blade Ground Fully Charged',
    '345': 'Flare Blade Air Start Charge',
    '346': 'Flare Blade Air Charge Loop',
    '347': 'Flare Blade Air Early Release',
    '348': 'Flare Blade Air Fully Charged',
    '349': 'Double Edge Dance 1 Ground',
    '350': 'Double Edge Dance 2 Up Ground',
    '351': 'Double Edge Dance 2 Side Ground',
    '352': 'Double Edge Dance 3 Up Ground',
    '353': 'Double Edge Dance 3 Side Ground',
    '354': 'Double Edge Dance 3 Down Ground',
    '355': 'Double Edge Dance 4 Up Ground',
    '356': 'Double Edge Dance 4 Side Ground',
    '357': 'Double Edge Dance 4 Down Ground',
    '358': 'Double Edge Dance 1 Air',
    '359': 'Double Edge Dance 2 Up Air',
    '360': 'Double Edge Dance 2 Side Air',
    '361': 'Double Edge Dance 3 Up Air',
    '362': 'Double Edge Dance 3 Side Air',
    '363': 'Double Edge Dance 3 Down Air',
    '364': 'Double Edge Dance 4 Up Air',
    '365': 'Double Edge Dance 4 Side Air',
    '366': 'Double Edge Dance 4 Down Air',
    '367': 'Blazer Ground',
    '368': 'Blazer Air',
    '369': 'Counter Ground',
    '370': 'Counter Ground Hit',
    '371': 'Counter Air',
    '372': 'Counter Air Hit',
  },
  // Samus
  13: {
    '341': 'Bomb Jump Ground',
    '342': 'Bomb Jump Air',
    '343': 'Charge Shot Ground Start',
    '344': 'Charge Shot Ground Loop',
    '345': 'Charge Shot Ground End',
    '346': 'Charge Shot Ground Fire',
    '347': 'Charge Shot Air Start',
    '348': 'Charge Shot Air Fire',
    '349': 'Missile Ground',
    '350': 'Missile Smash Ground',
    '351': 'Missile Air',
    '352': 'Missile Smash Air',
    '353': 'Screw Attack Ground',
    '354': 'Screw Attack Air',
    '355': 'Bomb End Ground',
    '356': 'Bomb Air',
    '357': 'Zair',
    '358': 'Zair Catch',
  },
  // Sheik
  7: {
    '341': 'Needle Storm Ground Start Charge',
    '342': 'Needle Storm Ground Charge Loop',
    '343': 'Needle Storm Ground End Charge',
    '344': 'Needle Storm Ground Fire',
    '345': 'Needle Storm Air Start Charge',
    '346': 'Needle Storm Air Charge Loop',
    '347': 'Needle Storm Air End Charge',
    '348': 'Needle Storm Air Fire',
    '349': 'Chain Ground Startup',
    '350': 'Chain Ground Loop',
    '351': 'Chain Ground End',
    '352': 'Chain Air Startup',
    '353': 'Chain Air Loop',
    '354': 'Chain Air End',
    '355': 'Vanish Ground Startup',
    '356': 'Vanish Ground Disappear',
    '357': 'Vanish Ground Reappear',
    '358': 'Vanish Air Startup',
    '359': 'Vanish Air Disappear',
    '360': 'Vanish Air Reappear',
    '361': 'Transform Ground',
    '362': 'Transform Ground Ending',
    '363': 'Transform Air',
    '364': 'Transform Air Ending',
  },
  // Yoshi
  14: {
    '341': 'Buffered Shield Startup?',
    '342': 'Shield Hold',
    '343': 'Shield Release',
    '344': 'Shield Damage',
    '345': 'Shield Startup',
    '346': 'Egg Lay Ground',
    '347': 'Egg Lay Ground Capture Start',
    '348': '???',
    '349': 'Egg Lay Ground Capture',
    '350': '???',
    '351': 'Egg Lay Air',
    '352': 'Egg Lay Air Capture Start',
    '353': '???',
    '354': 'Egg Lay Air Capture',
    '355': '???',
    '356': 'Egg Roll Ground Startup',
    '357': 'Egg Roll Ground',
    '358': 'Egg Roll Ground Change Direction',
    '359': 'Egg Roll Ground End',
    '360': 'Egg Roll Air Start',
    '361': 'Egg Roll Air',
    '362': 'Egg Roll Bounce',
    '363': 'Egg Roll Air End',
    '364': 'Egg Throw Ground',
    '365': 'Egg Throw Air',
    '366': 'Bomb Ground',
    '367': 'Bomb Land',
    '368': 'Bomb Air',
  },
  // Young Link
  20: {
    '341': 'Side Smash 2',
    '342': 'Taunt R',
    '343': 'Taunt L',
    '344': 'Fire Bow Ground Charge',
    '345': 'Fire Bow Ground Fully Charged',
    '346': 'Fire Bow Ground Fire',
    '347': 'Fire Bow Air Charge',
    '348': 'Fire Bow Air Fully Charged',
    '349': 'Fire Bow Air Fire',
    '350': 'Boomerang Ground Throw',
    '351': 'Boomerang Ground Catch',
    '352': 'Boomerang Ground Throw Empty',
    '353': 'Boomerang Air Throw',
    '354': 'Boomerang Air Catch',
    '355': 'Boomerang Air Throw Empty',
    '356': 'Spin Attack Ground',
    '357': 'Spin Attack Air',
    '358': 'Bomb Ground',
    '359': 'Bomb Air',
    '360': 'Zair',
    '361': 'Zair Catch',
  },
  // Zelda
  19: {
    '341': "Nayru's Love Ground",
    '342': "Nayru's Love Air",
    '343': "Din's Fire Ground Startup",
    '344': "Din's Fire Ground Travel",
    '345': "Din's Fire Ground Explode",
    '346': "Din's Fire Air Startup",
    '347': "Din's Fire Air Travel",
    '348': "Din's Fire Air Explode",
    '349': "Farore's Wind Ground",
    '350': "Farore's Wind Ground Disappear",
    '351': "Farore's Wind Ground Reappear",
    '352': "Farore's Wind Air",
    '353': "Farore's Wind Air Disappear",
    '354': "Farore's Wind Air Reappear",
    '355': 'Transform Ground',
    '356': 'Transform Ground Ending',
    '357': 'Transform Air',
    '358': 'Transform Air Ending',
  },
};
